baseURL = "https://ranco-disaster.netlify.com/"
languageCode = "en-us"
theme = "site-theme"
title = "Ranco Response"
enableRobotsTXT = true

[[menu.desktop]]
    identifier = "Emergency Response"
    name = "Emergency Response"
    url = "/emergency-response/"
    weight = 1
[[menu.desktop]]
    identifier = "Logistics Support"
    name = "Logistics Support"
    url = "/logistics-support/"
    weight = 2
[[menu.desktop]]
    identifier = "Event Support"
    name = "Event Support"
    url = "/event-support/"
    weight = 3
[[menu.desktop]]
    identifier = "Structures"
    name = "Structures"
    url = "/structures/"
    weight = 4
[[menu.desktop]]
    identifier = "Amenities"
    name = "Amenities"
    url = "/amenities/"
    weight = 5
[[menu.desktop]]
    identifier = "About Us"
    name = "About Us"
    url = "/about-us/"
    weight = 6
[[menu.desktop]]
    identifier = "Contact Us"
    name = "Contact Us"
    url = "/contact-us/"
    weight = 7
[[menu.mobile]]
    identifier = "Emergency Response"
    name = "Emergency Response"
    url = "/emergency-response/"
    weight = 1
[[menu.mobile]]
    identifier = "Logistics Support"
    name = "Logistics Support"
    url = "/logistics-support/"
    weight = 2
[[menu.mobile]]
    identifier = "Event Support"
    name = "Event Support"
    url = "/event-support/"
    weight = 3
[[menu.mobile]]
    identifier = "Structures"
    name = "Structures"
    url = "/structures/"
    weight = 4
[[menu.mobile]]
    identifier = "Amenities"
    name = "Amenities"
    url = "/amenities/"
    weight = 5
[[menu.mobile]]
    identifier = "Who we are"
    name = "Who we are"
    url = "/about-us/"
    weight = 6
[[menu.footer]]
    identifier = "Emergency Response"
    name = "Emergency Response"
    weight = 1
    [[menu.footer]]
        identifier = "Facilities Support"
        name = "Facilities Support"
        url = "/facilities-support/"
        parent = "Emergency Response"
        weight = 1
    [[menu.footer]]
        identifier = "Turn-key Camps"
        name = "Turn-key Camps"
        url = "/turnkey-camps/"
        parent = "Emergency Response"
        weight = 2
    [[menu.footer]]
        identifier = "Tactical Operations Center"
        name = "Tactical Operations Center"
        url = "/tactical-operations-centers/"
        parent = "Emergency Response"
        weight = 3
    [[menu.footer]]
        identifier = "Business Continuity"
        name = "Business Continuity"
        url = "/business-continuity/"
        parent = "Emergency Response"
        weight = 4
    [[menu.footer]]
        identifier = "LSA Support"
        name = "LSA Support"
        url = "/lsa-support/"
        parent = "Emergency Response"
        weight = 5
    [[menu.footer]]
        identifier = "Tents / Shelters"
        name = "Tents / Shelters"
        url = "/structures/"
        parent = "Emergency Response"
        weight = 6
[[menu.footer]]
    identifier = "Logistics Support"
    name = "Logistics Support"
    weight = 2
    [[menu.footer]]
        identifier = "Facilities Support 1"
        name = "Facilities Support"
        url = "/structures/"
        parent = "Logistics Support"
        weight = 1
[[menu.footer]]
    identifier = "event-support"
    name = "Event Support"
    url = "/event-support/"
    weight = 3
[[menu.footer]]
    identifier = "structures"
    name = "Structures"
    url = "/structures/"
    weight = 4
[[menu.footer]]
    identifier = "amenities"
    name = "Amenities"
    url = "/amenities/"
    weight = 5
[[menu.footer]]
    identifier = "about-us"
    name = "About Us"
    url = "/about-us/"
    weight = 6
[[menu.footer]]
    identifier = "contact-us"
    name = "Contact Us"
    url = "/contact-us/"
    weight = 7
[params.utilityImages]
    thankyouBackground = ""
[params.tracking]
    cloudinary_url = "https://res.cloudinary.com/pioneer-design/image/upload"
[params.socialLinks]
    facebook = ""
    insta = ""
    linkedin = ""
    pinterest = ""
[params.publishingSettings]
    siteinProduction = true

[mediaTypes]
  [mediaTypes."text/noExt"]
    suffixes = ""

[sitemap]
    filename = "sitepages.xml"

[outputFormats]
    [outputFormats.sitemapindex]
        baseName = "sitemapindex"
        isPlainText = false
        mediaType = "application/xml"
        path = "/"
    [outputFormats.sitepages]
        baseName = "sitepages"
        isPlainText = false
        mediaType = "application/xml"
        path = "/"
    [outputFormats.siteposts]
        baseName = "siteposts"
        isPlainText = false
        mediaType = "application/xml"
        path = "/"
    [outputFormats.redirects]
        baseName = "_redirects"
        isPlainText = true
        mediaType = "text/noExt"
        path = "/"
    [outputFormats.Algolia]
        baseName = "algolia"
        isPlainText = true
        mediaType = "application/json"
        notAlternative = true

[outputs]
  home = ["HTML", "sitemapindex", "sitepages", "siteposts", "RSS", "redirects", "Algolia"]

[params.algolia]
    appId = ""
    searchKey = ""
    indexName = ""

[params.extraTools]
    algoliaSearch = false
    fontAwesome = true
    floatingHeader = false