baseURL = "https://ranco-disaster.netlify.com/"
languageCode = "en-us"
theme = "site-theme"
title = "Ranco Response"
enableRobotsTXT = true

[params.meta]
description = "This domain is established to be used for illustrative examples in documents. You may use this domain in examples without prior coordination or asking for permission."

[[menu.desktop]]
    identifier = "emergency-response"
    name = "Emergency Response"
    url = "/emergency-response/"
    weight = 1
[[menu.desktop]]
    identifier = "logistics-support"
    name = "Logistics Support"
    url = "/logistics-support/"
    weight = 2
[[menu.desktop]]
    identifier = "event-support"
    name = "Event Support"
    url = "/event-support/"
    weight = 3
[[menu.desktop]]
    identifier = "structures"
    name = "Structures"
    url = "/structures/"
    weight = 4
[[menu.desktop]]
    identifier = "amenities"
    name = "Amenities"
    url = "/amenities/"
    weight = 5
[[menu.desktop]]
    identifier = "about-us"
    name = "About Us"
    url = "/about-us/"
    weight = 6
[[menu.desktop]]
    identifier = "contact-us"
    name = "Contact Us"
    url = "/contact-us/"
    weight = 7
[[menu.mobile]]
    identifier = "emergency-response"
    name = "Emergency Response"
    url = "/emergency-response/"
    weight = 1
[[menu.mobile]]
    identifier = "logistics-support"
    name = "Logistics Support"
    url = "/logistics-support/"
    weight = 2
[[menu.mobile]]
    identifier = "event-support"
    name = "Event Support"
    url = "/event-support/"
    weight = 3
[[menu.mobile]]
    identifier = "structures"
    name = "Structures"
    url = "/structures/"
    weight = 4
[[menu.mobile]]
    identifier = "amenities"
    name = "Amenities"
    url = "/amenities/"
    weight = 5
[[menu.mobile]]
    identifier = "about-us"
    name = "Who we are"
    url = "/about-us/"
    weight = 6
[params.contactNumbers]
    Fax = "555.555.5555"
    Phone = "555.555.5555"
[params.Logos]
    darkLogo = "/pageimg/RR.Horizontal.White.svg"
    logo = "/pageimg/RR.Horizontal.White.svg"
    mobileLogo = "/pageimg/RR.Horizontal.White.svg"
[params.utilityImages]
    thankyouBackground = "/pageimg/thank-you-contact.jpg"
[params.address]
    city = "Statesboro"
    state = "GA"
    street = "P.O. Box 134"
    zip = 30459
[params.email]
    email = "example@example.com"
[params.tracking]
    googleAnalytics = ""
    cloudinaryUrl = ""
[params.socialLinks]
    facebook = ""
    insta = ""
    linkedin = ""
    pinterest = ""
[params.publishingSettings]
    siteinProduction = false

[mediaTypes]
  [mediaTypes."text/noExt"]
    suffixes = ""

[sitemap]
    filename = "sitepages.xml"

[outputFormats]
    [outputFormats.sitemapindex]
        baseName = "sitemapindex"
        isPlainText = false
        mediaType = "application/xml"
        path = "/"
    [outputFormats.sitepages]
        baseName = "sitepages"
        isPlainText = false
        mediaType = "application/xml"
        path = "/"
    [outputFormats.siteposts]
        baseName = "siteposts"
        isPlainText = false
        mediaType = "application/xml"
        path = "/"
    [outputFormats.redirects]
        baseName = "_redirects"
        isPlainText = true
        mediaType = "text/noExt"
        path = "/"
    [outputFormats.Algolia]
        baseName = "algolia"
        isPlainText = true
        mediaType = "application/json"
        notAlternative = true

[outputs]
  home = ["HTML", "sitemapindex", "sitepages", "siteposts", "RSS", "redirects", "Algolia"]

[params.algolia]
    appId = ""
    searchKey = ""
    indexName = ""

[params.extraTools]
    algoliaSearch = false
    fontAwesome = true
    floatingHeader = false